In [1]:
import os
import json
import tensorflow as tf
from tf_transformers.models import ROBERTAEncoder, EncoderDecoder


In [2]:
from tf_transformers.utils import get_config, validate_model_name

allowed_model_names = ["roberta_base", "roberta_large"]


def modelWrapper(model_name, **kwargs):
    """Wrapper for Model

    Args:
        model_name ([type]): [description]

    Returns:
        [type]: [description]
    """

    name = "roberta"

    model_name = model_name.replace("-", "_")  # replace - with _
    validate_model_name(model_name, allowed_model_names)
    config = get_config("tf_transformers.models.model_configs.roberta", model_name)

    if "is_training" not in kwargs:
        kwargs["is_training"] = False
    checkpoint_dir = None
    if "checkpoint_dir" in kwargs:
        checkpoint_dir = kwargs["checkpoint_dir"]
        del kwargs["checkpoint_dir"]
    kwargs["name"] = name
    print("Kwargs", kwargs)
    model_layer = ROBERTAEncoder(config, **kwargs)
    model = model_layer.get_model()
    if checkpoint_dir:
        model.load_checkpoint(checkpoint_dir)
    return model_layer, model, config


from tf_transformers.utils import get_config, validate_model_name, get_model_wrapper
from tf_transformers.models import EncoderDecoder
from absl import logging

logging.set_verbosity("INFO")




In [3]:
model_layer, model, config = EncoderDecoderModel(model_name='roberta_base', 
                                                 is_training = False,
                                                 share_attention_layers=False,
                                                 share_encoder_embeddings=True, 
                                                 pipeline_mode="auto-regressive")
model.load_checkpoint("/Users/PRVATE/Documents/Tokenizers/tf_xsum_summarizer/")

INFO:absl:We are overwriding `is_training` is False to `is_training` to True with `use_dropout` is False, no effects on your inference pipeline
INFO:absl:Initialized Variables


Share attention layers False
Share attention layers False
Share attention layers False
Share attention layers False
Share attention layers False
Share attention layers False
Share attention layers False
Share attention layers False
Share attention layers False
Share attention layers False
Share attention layers False
Share attention layers False


INFO:absl:Initialized Variables
INFO:absl:Inputs -->
INFO:absl:encoder_input_ids ---> Tensor("input_ids:0", shape=(None, None), dtype=int32)
INFO:absl:encoder_input_mask ---> Tensor("input_mask:0", shape=(None, None), dtype=int32)
INFO:absl:encoder_input_type_ids ---> Tensor("input_type_ids:0", shape=(None, None), dtype=int32)
INFO:absl:decoder_input_ids ---> Tensor("decoder_input_ids:0", shape=(None, None), dtype=int32)
INFO:absl:decoder_input_type_ids ---> Tensor("decoder_input_type_ids:0", shape=(None, None), dtype=int32)
INFO:absl:decoder_all_cache_key ---> Tensor("all_cache_key:0", shape=(None, None, 12, None, 64), dtype=float32)
INFO:absl:decoder_all_cache_value ---> Tensor("all_cache_value:0", shape=(None, None, 12, None, 64), dtype=float32)
INFO:absl:encoder_hidden_states ---> Tensor("encoder_hidden_states:0", shape=(None, None, 768), dtype=float32)
INFO:absl:Initialized Variables
INFO:absl:Inputs -->
INFO:absl:encoder_input_ids ---> Tensor("input_ids:0", shape=(None, None), dt


Two checkpoint references resolved to different objects (<tf_transformers.models.encoder_decoder.EncoderDecoder object at 0x1800621f0> and <tensorflow.python.keras.engine.input_layer.InputLayer object at 0x144e40e20>).



Two checkpoint references resolved to different objects (<tf_transformers.models.encoder_decoder.EncoderDecoder object at 0x1800621f0> and <tensorflow.python.keras.engine.input_layer.InputLayer object at 0x144e40e20>).
INFO:absl:Succesful: Model checkpoints matched


In [13]:
model_layer, model, config = T5Model(model_name='t5-small', is_training=False, pipeline_mode='auto-regressive')

INFO:absl:We are overwriding `is_training` is False to `is_training` to                     True with `use_dropout` is False, no effects on your inference pipeline
INFO:absl:Initialized Variables
INFO:absl:Initialized Variables
INFO:absl:Inputs -->
INFO:absl:encoder_input_ids ---> Tensor("input_ids:0", shape=(None, None), dtype=int32)
INFO:absl:encoder_input_mask ---> Tensor("input_mask:0", shape=(None, None), dtype=int32)
INFO:absl:decoder_input_ids ---> Tensor("decoder_input_ids:0", shape=(None, None), dtype=int32)
INFO:absl:decoder_all_cache_key ---> Tensor("all_cache_key:0", shape=(None, None, 8, None, 64), dtype=float32)
INFO:absl:decoder_all_cache_value ---> Tensor("all_cache_value:0", shape=(None, None, 8, None, 64), dtype=float32)
INFO:absl:encoder_hidden_states ---> Tensor("encoder_hidden_states:0", shape=(None, None, 512), dtype=float32)
INFO:absl:Initialized Variables
INFO:absl:Inputs -->
INFO:absl:encoder_input_ids ---> Tensor("input_ids:0", shape=(None, None), dtype=int32)

In [14]:
model.load_checkpoint("/Users/PRVATE/tf_transformers_models/t5-small/")


Two checkpoint references resolved to different objects (<tf_transformers.models.encoder_decoder.EncoderDecoder object at 0x1389afbe0> and <tensorflow.python.keras.engine.input_layer.InputLayer object at 0x158cb0dc0>).



Two checkpoint references resolved to different objects (<tf_transformers.models.encoder_decoder.EncoderDecoder object at 0x1389afbe0> and <tensorflow.python.keras.engine.input_layer.InputLayer object at 0x158cb0dc0>).
INFO:absl:Succesful: Model checkpoints matched


In [5]:
model_layer_test, model_test, config = EncoderDecoderModel(model_name='roberta_base', is_training=False)

INFO:absl:We are overwriding `is_training` is False to `is_training` to True with `use_dropout` is False, no effects on your inference pipeline
INFO:absl:Initialized Variables
INFO:absl:Initialized Variables
INFO:absl:Inputs -->
INFO:absl:encoder_input_ids ---> Tensor("input_ids:0", shape=(None, None), dtype=int32)
INFO:absl:encoder_input_mask ---> Tensor("input_mask:0", shape=(None, None), dtype=int32)
INFO:absl:encoder_input_type_ids ---> Tensor("input_type_ids:0", shape=(None, None), dtype=int32)
INFO:absl:decoder_input_ids ---> Tensor("decoder_input_ids:0", shape=(None, None), dtype=int32)
INFO:absl:decoder_input_type_ids ---> Tensor("decoder_input_type_ids:0", shape=(None, None), dtype=int32)
INFO:absl:decoder_all_cache_key ---> Tensor("all_cache_key:0", shape=(None, None, 12, None, 64), dtype=float32)
INFO:absl:decoder_all_cache_value ---> Tensor("all_cache_value:0", shape=(None, None, 12, None, 64), dtype=float32)
INFO:absl:encoder_hidden_states ---> Tensor("encoder_hidden_state

In [32]:
tf.keras.backend.clear_session()

# tf_transformers Layer (an extension of Keras Layer)
# This is not Keras model, but extension of keras Layer

encoder_layer = ROBERTAEncoder(config=config['encoder'],
                      name='roberta',
                      mask_mode='user_defined',
                      is_training=False
                      )

tf.keras.backend.clear_session()
decoder_layer = ROBERTAEncoder(config=config['encoder'],
                      name='roberta',
                      mask_mode='causal',
                      is_training=False,
                      is_decoder = True, 
                      use_mlm_layer = True,
                      share_attention_layers = False, 
                      share_encoder_embeddings = True, 
                      encoder_embedding_layer=encoder_layer._embedding_layer,
                      encoder_type_embedding_layer=encoder_layer._type_embeddings,
                      encoder_positional_embedding_layer=encoder_layer._position_embedding_layer
                      
                              )
len(decoder_layer.variables)

INFO:absl:We are overwriding `is_training` is False to `is_training` to True with `use_dropout` is False, no effects on your inference pipeline
INFO:absl:Initialized Variables
INFO:absl:We are overwriding `is_training` is False to `is_training` to True with `use_dropout` is False, no effects on your inference pipeline


Share attention layers False
Share attention layers False
Share attention layers False
Share attention layers False
Share attention layers False
Share attention layers False
Share attention layers False
Share attention layers False
Share attention layers False
Share attention layers False
Share attention layers False
Share attention layers False


INFO:absl:Initialized Variables


320

In [33]:
for var in decoder_layer.variables:
    print(var.name, var.shape)

tf_transformers/last_logits_bias:0 (50265,)
tf_transformers/roberta/word_embeddings/embeddings:0 (50265, 768)
tf_transformers/roberta/type_embeddings/embeddings:0 (1, 768)
tf_transformers/roberta/positional_embeddings/embeddings:0 (512, 768)
tf_transformers/roberta/transformer/layer_0/self_attention/query/kernel:0 (768, 12, 64)
tf_transformers/roberta/transformer/layer_0/self_attention/query/bias:0 (12, 64)
tf_transformers/roberta/transformer/layer_0/self_attention/key/kernel:0 (768, 12, 64)
tf_transformers/roberta/transformer/layer_0/self_attention/key/bias:0 (12, 64)
tf_transformers/roberta/transformer/layer_0/self_attention/value/kernel:0 (768, 12, 64)
tf_transformers/roberta/transformer/layer_0/self_attention/value/bias:0 (12, 64)
tf_transformers/roberta/transformer/layer_0/self_attention_output/kernel:0 (768, 768)
tf_transformers/roberta/transformer/layer_0/self_attention_output/bias:0 (768,)
tf_transformers/roberta/transformer/layer_0/self_attention_layer_norm/gamma:0 (768,)
tf_t

In [36]:
tf.keras.backend.clear_session()
model2 = EncoderDecoder(encoder=encoder_layer, 
                       decoder=decoder_layer, 
                       is_training=True, 
                       name = 'bert2bertaaa')
model2 = model2.get_model()
len(model2.variables)

INFO:absl:Inputs -->
INFO:absl:encoder_input_ids ---> Tensor("input_ids:0", shape=(None, None), dtype=int32)
INFO:absl:encoder_input_mask ---> Tensor("input_mask:0", shape=(None, None), dtype=int32)
INFO:absl:encoder_input_type_ids ---> Tensor("input_type_ids:0", shape=(None, None), dtype=int32)
INFO:absl:decoder_input_ids ---> Tensor("decoder_input_ids:0", shape=(None, None), dtype=int32)
INFO:absl:decoder_input_type_ids ---> Tensor("decoder_input_type_ids:0", shape=(None, None), dtype=int32)
INFO:absl:Initialized Variables
INFO:absl:Inputs -->
INFO:absl:encoder_input_ids ---> Tensor("input_ids:0", shape=(None, None), dtype=int32)
INFO:absl:encoder_input_mask ---> Tensor("input_mask:0", shape=(None, None), dtype=int32)
INFO:absl:encoder_input_type_ids ---> Tensor("input_type_ids:0", shape=(None, None), dtype=int32)
INFO:absl:decoder_input_ids ---> Tensor("decoder_input_ids:0", shape=(None, None), dtype=int32)
INFO:absl:decoder_input_type_ids ---> Tensor("decoder_input_type_ids:0", sha

516

In [37]:
model2.load_checkpoint("/Users/PRVATE/Documents/Tokenizers/tf_xsum_summarizer")

INFO:absl:Succesful: Model checkpoints matched


In [2]:
# Default configs for the model
model_config_dir = '/Users/PRVATE/Documents/tf_transformers/src/tf_transformers/models/model_configs/'

model_name = 'roberta_base'
config_location = os.path.join(model_config_dir, model_name, 'config.json')
config = json.load(open(config_location))
# config['num_hidden_layers'] = 1
# Always do this
tf.keras.backend.clear_session()

# tf_transformers Layer (an extension of Keras Layer)
# This is not Keras model, but extension of keras Layer

encoder_layer = ROBERTAEncoder(config=config,
                      name='roberta',
                      mask_mode=config['mask_mode'],
                      is_training=False
                      )

tf.keras.backend.clear_session()
decoder_layer = ROBERTAEncoder(config=config,
                      name='roberta',
                      mask_mode='causal',
                      is_training=False,
                      is_decoder = True, 
                      use_mlm_layer = True,
                      share_attention_layers = False, 
                      share_encoder_embeddings = True, 
                      encoder_embedding_layer=encoder_layer._embedding_layer,
                      encoder_type_embedding_layer=encoder_layer._type_embeddings,
                      encoder_positional_embedding_layer=encoder_layer._position_embedding_layer
                      
                              )

tf.keras.backend.clear_session()
model = EncoderDecoder(encoder=encoder_layer, 
                       decoder=decoder_layer, 
                       is_training=True, 
                       name = 'bert2bert')
model = model.get_model()
model.load_checkpoint("/Users/PRVATE/Documents/Tokenizers/tf_xsum_summarizer/")

FileNotFoundError: [Errno 2] No such file or directory: '/Users/PRVATE/Documents/tf_transformers/src/tf_transformers/models/model_configs/roberta_base/config.json'

In [3]:
model.model_config

{'encoder': {'initializer': {'class_name': 'TruncatedNormal',
   'config': {'mean': 0.0, 'stddev': 0.02, 'seed': None}},
  'is_training': True,
  'use_dropout': False,
  'batch_size': None,
  'sequence_length': None,
  'name': 'tf_transformers/roberta',
  'use_type_embeddings': True,
  'use_positonal_embeddings': True,
  'is_decoder': False,
  'share_encoder_embeddings': False,
  'share_attention_layers': True,
  'cross_attention_inside_encoder': False,
  'attention_probs_dropout_prob': 0.1,
  'hidden_act': 'gelu',
  'intermediate_act': 'gelu',
  'hidden_dropout_prob': 0.1,
  'embedding_size': 768,
  'initializer_range': 0.02,
  'intermediate_size': 3072,
  'max_position_embeddings': 512,
  'num_attention_heads': 12,
  'num_hidden_layers': 12,
  'type_vocab_size': 1,
  'vocab_size': 50265,
  'layer_norm_epsilon': 1e-05,
  'mask_mode': 'user_defined'},
 'decoder': {'initializer': {'class_name': 'TruncatedNormal',
   'config': {'mean': 0.0, 'stddev': 0.02, 'seed': None}},
  'is_training'

In [37]:
# Default configs for the model
model_config_dir = '/Users/PRVATE/Documents/tf_transformers/src/tf_transformers/models/model_configs/'

model_name = 'roberta_base'
config_location = os.path.join(model_config_dir, model_name, 'config.json')
config = json.load(open(config_location))
# config['num_hidden_layers'] = 1
# Always do this
tf.keras.backend.clear_session()

# tf_transformers Layer (an extension of Keras Layer)
# This is not Keras model, but extension of keras Layer

encoder_layer = ROBERTAEncoder(config=config,
                      name='roberta',
                      mask_mode=config['mask_mode'],
                      is_training=False
                      )

tf.keras.backend.clear_session()
decoder_layer = ROBERTAEncoder(config=config,
                      name='roberta',
                      mask_mode='causal',
                      is_training=False,
                      is_decoder = True,
                      pipeline_mode='auto-regressive',
                      use_mlm_layer = True,
                      share_attention_layers = False, 
                      share_encoder_embeddings = True, 
                      encoder_embedding_layer=encoder_layer._embedding_layer,
                      encoder_type_embedding_layer=encoder_layer._type_embeddings,
                      encoder_positional_embedding_layer=encoder_layer._position_embedding_layer
                      
                              )

tf.keras.backend.clear_session()
model_test = EncoderDecoder(encoder=encoder_layer, 
                       decoder=decoder_layer, 
                       is_training=False, 
                       name = 'bert2bert')
model_test = model_test.get_model()
model_test.load_checkpoint("/Users/PRVATE/Documents/Tokenizers/tf_xsum_summarizer/")

INFO:absl:We are overwriding `is_training` is False to `is_training` to True with `use_dropout` is False, no effects on your inference pipeline
INFO:absl:Initialized Variables
INFO:absl:Initialized Variables
INFO:absl:Inputs -->
INFO:absl:encoder_input_ids ---> Tensor("input_ids:0", shape=(None, None), dtype=int32)
INFO:absl:encoder_input_mask ---> Tensor("input_mask:0", shape=(None, None), dtype=int32)
INFO:absl:encoder_input_type_ids ---> Tensor("input_type_ids:0", shape=(None, None), dtype=int32)
INFO:absl:decoder_input_ids ---> Tensor("decoder_input_ids:0", shape=(None, None), dtype=int32)
INFO:absl:decoder_input_type_ids ---> Tensor("decoder_input_type_ids:0", shape=(None, None), dtype=int32)
INFO:absl:decoder_all_cache_key ---> Tensor("all_cache_key:0", shape=(None, None, 12, None, 64), dtype=float32)
INFO:absl:decoder_all_cache_value ---> Tensor("all_cache_value:0", shape=(None, None, 12, None, 64), dtype=float32)
INFO:absl:encoder_hidden_states ---> Tensor("encoder_hidden_state


Two checkpoint references resolved to different objects (<tf_transformers.models.encoder_decoder.EncoderDecoder object at 0x151e16c40> and <tensorflow.python.keras.engine.input_layer.InputLayer object at 0x14ef6df70>).



Two checkpoint references resolved to different objects (<tf_transformers.models.encoder_decoder.EncoderDecoder object at 0x151e16c40> and <tensorflow.python.keras.engine.input_layer.InputLayer object at 0x14ef6df70>).
INFO:absl:Succesful: Model checkpoints matched


In [4]:
import datasets
data = datasets.load_from_disk("/Users/PRVATE/HUggingFace_Models/dataset/cnn_dailymail/")

In [5]:
from transformers import RobertaTokenizer
tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

train_data = data["train"].select(range(100))

In [6]:
from tf_transformers.data import pad_dataset
encoder_max_length=512
decoder_max_length=64
batch_size = 2

@pad_dataset
def process_data_to_model_inputs(text_list):
    
    # Tokenizer will automatically set [BOS] <text> [EOS]  
    inputs = tokenizer(text_list, padding="max_length", truncation=True, max_length=encoder_max_length)
    tokenized = {}
    tokenized["encoder_input_ids"] = inputs.input_ids                                                               
    tokenized["encoder_input_mask"] = inputs.attention_mask  
    tokenized["encoder_input_type_ids"] = tf.zeros_like(inputs.attention_mask).numpy()

    return tokenized  

In [34]:
sample_data = train_data.select(range(2))
article_list = [item['article'] for item in list(sample_data)]
encoded_inputs = process_data_to_model_inputs(article_list)

In [42]:
model_test.save_checkpoint("temp", overwrite=True)

INFO:absl:Saved model at temp/ckpt-1


In [43]:
model_test.save_as_serialize_module("temp_pb_module/", overwrite=True)

Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.


Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.


Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.


Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.


INFO:tensorflow:Assets written to: temp_pb_module/assets


INFO:tensorflow:Assets written to: temp_pb_module/assets


In [14]:
loaded = tf.saved_model.load("temp_pb_module/")
model_pb = loaded.signatures['serving_default']

In [115]:
from tf_transformers.text import TextDecoderSeq2Seq
decoder = TextDecoderSeq2Seq(
    model = model_test,
    decoder_start_token_id = 0,
    decoder_input_type_ids = 0
)

# decoder_results = decoder.decode(encoded_inputs, 
#                mode='beam', 
#                beam_size=3,
#                max_iterations=64, 
#                eos_id=2)
decoder_results = decoder.decode(encoded_inputs, 
               mode='top_k_top_p', 
               top_k = 35,
               top_p =0.55,
               num_return_sequences=3,
               max_iterations=64, 
               eos_id=2)
# decoder_results = decoder.decode(encoded_inputs, 
#                mode='greedy', 
#                max_iterations=64, 
#                eos_id=2)

In [116]:
decoder_results['predicted_ids']

<tf.Tensor: shape=(2, 3, 27), dtype=int32, numpy=
array([[[ 6517,  1284,    34,   553,  1148,     7,  2625,   549,     5,
           382,   197,   304,   831,   814,   136,  1854,   114,    24,
            16,    45,  4968,    31,   634,  4747,  2398,     4,     2],
        [ 6517,  1284,    34,   553,  1148,     7,  2625,   549,     5,
           382,   197,   304,   831,   814,   136,  1854,   114,    24,
            16,    45,  4968,    31,   634,  4747,  2398,     4,     2],
        [ 6517,  1284,    34,   553,  1148,     7,  2625,   549,     5,
           382,   197,   304,   831,   814,   136,  1854,   114,    24,
            16,    45,  4968,    31,   634,  4747,  2398,     4,     2]],

       [[  133,   232,    18,   144,  1800,  4131,    33,   351,  1637,
         10214,    11,     5,   604,    18,   727,   119, 12937,    23,
             5,   623,  8641,    11,  3467,     4,     2,     1,     1],
        [  133,   232,    18,   144,  1800,  4131,    33,   351,  1637,
        

In [117]:
decoder_results['matched_eos_pos']

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([25, 25, 25, 23, 23, 23], dtype=int32)>

In [40]:
tokenizer.decode(decoder_results['predicted_ids'][0][0])

'President Barack Obama has asked Congress to debate whether the US should use military action against Syria if it fails to stop the chemical weapons attack.</s><pad><pad><pad><pad><pad>'

In [41]:
tokenizer.decode(decoder_results['predicted_ids'][1][0])

"Great Britain won gold medals at the World Athletics Championships in Moscow on Sunday, with the men's 100m relay team winning gold.</s><pad><pad><pad><pad><pad><pad>"

In [67]:
decoder_results['matched_eos_pos']

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([27, 27, 28, 26, 30, 32], dtype=int32)>

In [110]:
# decoder_layer = TextDecoderSerializableSeq2Seq(
#     model = model_test,
#     decoder_start_token_id = 0,
#     decoder_input_type_ids = 0,
#     max_iterations=None,
#     mode="greedy",
#     do_sample=False,
#     eos_id=2,
# )
# # Convert whole operation to a model
# decoder_model  = decoder_layer.get_model()


# decoder_layer = TextDecoderSerializableSeq2Seq(
#     model = model_test,
#     decoder_start_token_id = 0,
#     decoder_input_type_ids = 0,
#     max_iterations=None,
#     mode="beam",
#     beam_size=3,
#     do_sample=False,
#     eos_id=2,
# )
# # Convert whole operation to a model
# decoder_model  = decoder_layer.get_model()

decoder_layer = TextDecoderSerializableSeq2Seq(
    model = model_test,
    decoder_start_token_id = 0,
    decoder_input_type_ids = 0,
    max_iterations=None,
    mode="top_k_top_p",
    top_k = 35, 
    top_p = 0.55,
    num_return_sequences=3,
    do_sample=False,
    eos_id=2,
)
# Convert whole operation to a model
decoder_model  = decoder_layer.get_model()

# decoder_module = LegacyModule(decoder_model)
# decoder_module.save(saved_model_dir_strategy)
# print("Saved")

In [111]:
encoded_inputs_copy = encoded_inputs.copy()
encoded_inputs_copy['iterations'] = tf.constant([[64]])

In [112]:
decoder_results_serialized = decoder_model(encoded_inputs_copy)

In [118]:
decoder_results['matched_eos_pos']

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([25, 25, 25, 23, 23, 23], dtype=int32)>

In [113]:
decoder_results_serialized['matched_eos_pos']

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([25, 25, 25, 23, 23, 23], dtype=int32)>

In [119]:
tf.assert_equal(decoder_results['predicted_ids'], decoder_results_serialized['predicted_ids'])