In [1]:
import sys
sys.path.append("/Users/sarathrnair/Projects/tf-transformers/src/")

In [2]:
import tensorflow as tf
from unet import UnetModel

/Users/sarathrnair/miniforge3/envs/venv_tf_mac/lib/python3.9/site-packages/jax/_src/lib/__init__.py:34: UserWarning: JAX on Mac ARM machines is experimental and minimally tested. Please see https://github.com/google/jax/issues/5501 in the event of problems.
  warnings.warn("JAX on Mac ARM machines is experimental and minimally tested. "


In [3]:
batch_size = 4
text_sequence_length = 96
text_embedding_dimension = 512
height = 64
width  = 64
in_channels = 3
time_steps = 1000

In [8]:
x = tf.random.uniform((batch_size, height, width, in_channels)) # original image
x_t = tf.random.uniform((batch_size, height, width, in_channels)) # noise image

t = tf.random.uniform(minval=0, maxval=time_steps, shape=(batch_size,), dtype=tf.int32) # time steps

time_embeddings = tf.random.uniform((batch_size, text_embedding_dimension))
text_token_embeddings = tf.random.uniform((batch_size, text_sequence_length, text_embedding_dimension))
sentence_embeddings = tf.reduce_mean(text_token_embeddings, axis=1)

In [9]:
out_channels = 512
channel_mult = [1, 2, 3, 4]
num_res_blocks = 3
per_head_channels = 64
attn_resolutions = [32, 16, 8]
embed_dim = 512
scale_shift_norm = True 

In [10]:
unet = UnetModel(
                out_channels=out_channels
                )
unet = unet.get_model()

In [11]:
text_input_mask = tf.random.uniform(minval=0, maxval=2, shape=(batch_size, text_token_embeddings.shape[1]), dtype=tf.int32
                                   )


In [12]:
inputs = {}
inputs['input_pixels'] = x_t # B x H x W x C
inputs['time_embeddings'] = time_embeddings # B x emb
inputs['text_token_embeddings'] = text_token_embeddings # B x S x emb_dim
inputs['sentence_embeddings'] = sentence_embeddings # B x emb_dim
inputs['text_input_mask'] = text_input_mask # B x S

In [13]:
h = unet(inputs)

In [10]:
len(unet.variables)

276

In [11]:
unet.count_params()

532105216

In [14]:
h['h']

<tf.Tensor: shape=(4, 64, 64, 512), dtype=float32, numpy=
array([[[[-6.78739548e-02, -1.17296129e-02, -1.80186331e-01, ...,
           4.06124741e-02, -3.10249329e-01, -3.54909658e-01],
         [-4.33969229e-01,  3.60139221e-01, -4.40992415e-02, ...,
          -4.32167798e-02, -3.31724107e-01, -3.40447873e-01],
         [-2.63214201e-01,  6.15860939e-01, -1.63929671e-01, ...,
          -1.33037701e-01,  1.76851690e-01, -3.70404780e-01],
         ...,
         [-2.06699312e-01,  4.76081491e-01,  1.53655075e-02, ...,
          -3.15815210e-01,  2.70729810e-02, -6.52103543e-01],
         [-1.91955149e-01,  4.10411894e-01, -1.43830523e-01, ...,
          -2.93969810e-01, -1.52241230e-01, -3.76308650e-01],
         [ 9.03505981e-02,  9.97426212e-02,  2.85856843e-01, ...,
          -1.78902671e-01, -2.16540098e-01, -4.85468209e-02]],

        [[-3.02216351e-01,  1.57548487e-03,  2.39374712e-01, ...,
           3.47710907e-01, -2.17092037e-02,  1.46035030e-02],
         [-7.40358412e-01,  7.

In [15]:
x = tf.random.uniform((1, 768))

In [18]:
tf.squeeze(x, axis=0)

<tf.Tensor: shape=(768,), dtype=float32, numpy=
array([0.6612359 , 0.7229481 , 0.34513712, 0.01766133, 0.05406225,
       0.6666049 , 0.00961912, 0.02549767, 0.01500332, 0.9168922 ,
       0.47627544, 0.68766034, 0.8866292 , 0.27564406, 0.73610425,
       0.78797376, 0.0842706 , 0.55637884, 0.08303356, 0.26995206,
       0.01106536, 0.5005944 , 0.51162183, 0.18929148, 0.0363673 ,
       0.3663795 , 0.04337323, 0.80921996, 0.5470406 , 0.2939397 ,
       0.45061445, 0.6238754 , 0.64394414, 0.19557679, 0.60766685,
       0.35204482, 0.25377572, 0.16472483, 0.1824156 , 0.8383397 ,
       0.42195308, 0.28824902, 0.06017482, 0.10863566, 0.94030344,
       0.11626852, 0.7232002 , 0.89658093, 0.2454294 , 0.19464087,
       0.0239836 , 0.64488626, 0.856081  , 0.40232885, 0.13125181,
       0.68138707, 0.5339943 , 0.05562246, 0.9647467 , 0.48236072,
       0.9632764 , 0.14239585, 0.9561063 , 0.53284633, 0.62722826,
       0.62361145, 0.6605511 , 0.66151595, 0.4217627 , 0.7303337 ,
       0.45785