In [1]:
import sys
sys.path.append("/Users/PRVATE/Documents/tf_transformers/src/")

In [6]:
from transformers import TFBertModel
from tf_transformers.models import BERTEncoder

import tensorflow as tf
import json

from tf_transformers.utils import convert_bert_hf_to_tf_transformers
import os

In [4]:
# Load HF model

# Always do this
tf.keras.backend.clear_session()

model_hf_location = '/Users/PRVATE/HUggingFace_Models/bert_base_uncased/'
model_hf = TFBertModel.from_pretrained(model_hf_location)

All model checkpoint layers were used when initializing TFBertModel.

All the layers of TFBertModel were initialized from the model checkpoint at /Users/PRVATE/HUggingFace_Models/bert_base_uncased/.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [7]:
# Load tf_transformers model
# Most config we will be providing

# Default configs for the model
# Default configs for the model
model_config_dir = '/Users/PRVATE/Documents/tf_transformers/model_configs/'
model_name = 'bert_base'
config_location = os.path.join(model_config_dir, model_name, 'config.json')
config = json.load(open(config_location))
# Always do this
tf.keras.backend.clear_session()
# Always do this
tf.keras.backend.clear_session()

# tf_transformers Layer (an extension of Keras Layer)
# This is not Keras model, but extension of keras Layer


model_layer = BERTEncoder(config=config,
                      name='bert',
                      mask_mode=config['mask_mode'],
                      is_training=False, 
                      use_dropout=False,
                      )
# model_dir = None, because we have not initialized the model with proper variable values
model_tf_transformers = model_layer.get_and_load_model(model_dir=None)

INFO:absl:We are overwriding `is_training` is False to `is_training` to                     True with `use_dropout` is False, no effects on your                         inference pipeline
INFO:absl:Inputs -->
INFO:absl:input_ids ---> Tensor("input_ids:0", shape=(None, None), dtype=int32)
INFO:absl:input_mask ---> Tensor("input_mask:0", shape=(None, None), dtype=int32)
INFO:absl:input_type_ids ---> Tensor("input_type_ids:0", shape=(None, None), dtype=int32)


Bert
Bert Encoder
Attention probs Tensor("tf_transformers/bert/transformer/layer_0/self_attention/masked_softmax/Softmax:0", shape=(None, 12, None, None), dtype=float32)
Bert
Bert Encoder
Attention probs Tensor("tf_transformers/bert/transformer/layer_1/self_attention/masked_softmax_1/Softmax:0", shape=(None, 12, None, None), dtype=float32)
Bert
Bert Encoder
Attention probs Tensor("tf_transformers/bert/transformer/layer_2/self_attention/masked_softmax_2/Softmax:0", shape=(None, 12, None, None), dtype=float32)
Bert
Bert Encoder
Attention probs Tensor("tf_transformers/bert/transformer/layer_3/self_attention/masked_softmax_3/Softmax:0", shape=(None, 12, None, None), dtype=float32)
Bert
Bert Encoder
Attention probs Tensor("tf_transformers/bert/transformer/layer_4/self_attention/masked_softmax_4/Softmax:0", shape=(None, 12, None, None), dtype=float32)
Bert
Bert Encoder
Attention probs Tensor("tf_transformers/bert/transformer/layer_5/self_attention/masked_softmax_5/Softmax:0", shape=(None, 12

INFO:absl:Initialized Variables
INFO:absl:Inputs -->
INFO:absl:input_ids ---> Tensor("input_ids_1:0", shape=(None, None), dtype=int32)
INFO:absl:input_mask ---> Tensor("input_mask_1:0", shape=(None, None), dtype=int32)
INFO:absl:input_type_ids ---> Tensor("input_type_ids_1:0", shape=(None, None), dtype=int32)


Bert
Bert Encoder
Attention probs Tensor("tf_transformers/bert/transformer/layer_11/self_attention/masked_softmax_11/Softmax:0", shape=(None, 12, None, None), dtype=float32)
Bert
Bert Encoder
Attention probs Tensor("tf_transformers/bert/transformer/layer_0/self_attention/masked_softmax/Softmax_1:0", shape=(None, 12, None, None), dtype=float32)
Bert
Bert Encoder
Attention probs Tensor("tf_transformers/bert/transformer/layer_1/self_attention/masked_softmax_1/Softmax_1:0", shape=(None, 12, None, None), dtype=float32)
Bert
Bert Encoder
Attention probs Tensor("tf_transformers/bert/transformer/layer_2/self_attention/masked_softmax_2/Softmax_1:0", shape=(None, 12, None, None), dtype=float32)
Bert
Bert Encoder
Attention probs Tensor("tf_transformers/bert/transformer/layer_3/self_attention/masked_softmax_3/Softmax_1:0", shape=(None, 12, None, None), dtype=float32)
Bert
Bert Encoder
Attention probs Tensor("tf_transformers/bert/transformer/layer_4/self_attention/masked_softmax_4/Softmax_1:0", sha

In [8]:
convert_bert_hf_to_tf_transformers(model_hf, model_tf_transformers, config)

INFO:absl:Deleteing huggingface model for saving memory
INFO:absl:Done assigning variables weights. Total 199


In [9]:
# Please have a look at tf_transformers/extra/reference_bert_cased.py for reference values

input_ids  = tf.constant([[1, 9, 10, 11, 23], 
                         [1, 22, 234, 432, 2349]])
input_mask = tf.ones_like(input_ids)
input_type_ids = tf.ones_like(input_ids)

inputs = {'input_ids': input_ids, 
          'input_mask': input_mask, 
          'input_type_ids': input_type_ids}

results_tf_transformers   = model_tf_transformers(inputs)
for k, r in results_tf_transformers.items():
    if isinstance(r, list):
        continue
    print(k, '-->', tf.reduce_sum(r), '-->', r.shape)

Bert
Bert Encoder
Attention probs tf.Tensor(
[[[[0.15948695 0.21239457 0.2071229  0.1968301  0.2241654 ]
   [0.14896567 0.17377833 0.21744183 0.21158165 0.2482326 ]
   [0.12204857 0.17939627 0.22291028 0.2225278  0.25311702]
   [0.12258875 0.1882031  0.23160318 0.21388346 0.24372163]
   [0.12147565 0.19426782 0.23870103 0.21341357 0.23214196]]

  [[0.9386795  0.01773462 0.01468536 0.01442256 0.01447799]
   [0.23429212 0.1638286  0.18610272 0.20874573 0.2070308 ]
   [0.25918669 0.15792762 0.16877808 0.20915006 0.20495754]
   [0.2565859  0.16245519 0.17455786 0.20216829 0.20423278]
   [0.20352589 0.16995424 0.19217037 0.22498478 0.20936482]]

  [[0.94563204 0.01941709 0.01336979 0.01101783 0.01056325]
   [0.66537434 0.20474236 0.05477256 0.05728903 0.01782167]
   [0.23272309 0.69185007 0.03932187 0.01292507 0.02317999]
   [0.21917284 0.11366016 0.587953   0.05922459 0.01998942]
   [0.27468792 0.03023142 0.04296448 0.5964459  0.05567029]]

  [[0.92104906 0.03281185 0.01738115 0.01587776 0

cls_output --> tf.Tensor(-10.324546, shape=(), dtype=float32) --> (2, 768)
token_embeddings --> tf.Tensor(-99.82982, shape=(), dtype=float32) --> (2, 5, 768)
token_logits --> tf.Tensor(-4488.868, shape=(), dtype=float32) --> (2, 5, 30522)
last_token_logits --> tf.Tensor(199.83713, shape=(), dtype=float32) --> (2, 30522)


In [18]:
# Huggingface Model
input_ids  = tf.constant([[1, 9, 10, 11, 23], 
                         [1, 22, 234, 432, 2349]])
input_mask = tf.ones_like(input_ids)
input_type_ids = tf.ones_like(input_ids)

results_hf = model_hf([input_ids, input_mask, input_type_ids])
for k in results_hf:
    print(k)
    print(tf.reduce_sum(results_hf[k]), '-->', results_hf[k].shape)

last_hidden_state
tf.Tensor(-99.29463, shape=(), dtype=float32) --> (2, 5, 768)
pooler_output
tf.Tensor(-10.38325, shape=(), dtype=float32) --> (2, 768)


In [19]:
model_tf_transformers.save_checkpoint("/Users/PRVATE/tf_transformers_models/bert_base_uncased")

INFO:absl:Saved model at /Users/PRVATE/tf_transformers_models/bert_base_uncased/ckpt-1
